# Nickname display time
display-time: 3

# Nickname display format
# Use & for colors, and use %  for papi values (for nickname use %player_name%)
name-format: "&a&l%player_name%"

# Change player's name with an invisible character
use-invisible-character: false

# Type of invisible character (available options: ZWSP, NBSP, ZWNJ, ZWJ)
# ZWSP - Zero-Width Space (U+200B) - invisible zero-width gap
# NBSP - Non-Breaking Space (U+00A0) - unbreakable gap
# ZWNJ - Zero-Width Non-Joiner (U+200C) - invisible separator
# ZWJ - Zero-Width Joiner (U+200D) - invisible connector
invisible-character-type: ZWSP

# Hide player's name in tab (списке игроков)
hide-in-tab-list: false

# Message settings
messages:
  reload-success: "&aRMBNametags: Config was successfully reload!"
  name-visible: "&aPlayer name &f%player_name%&a now hidden."
  name-hidden: "&aPlayer name &f%player_name%&a now visible."
  all-names-visible: "&aAll player's name became hidden."
  all-names-hidden: "&aAll player's name became visible."
  player-not-found: "&cPlayer &f%player_name%&c not found or offline."
  no-permission: "&cYou don't have permission to use this command."
