# display time in seconds
display-time: 3

# Change nickname format here
# Use & for colors and {PLAYER_NAME} variable
name-format: "&a&l%player_name%"

# Заменять ники игроков на невидимый символ
use-invisible-character: false

# Тип невидимого символа (доступные варианты: ZWSP, NBSP, ZWNJ, ZWJ)
# ZWSP - Zero-Width Space (U+200B) - невидимый пробел нулевой ширины
# NBSP - Non-Breaking Space (U+00A0) - неразрывный пробел
# ZWNJ - Zero-Width Non-Joiner (U+200C) - невидимый разделитель
# ZWJ - Zero-Width Joiner (U+200D) - невидимый соединитель
invisible-character-type: ZWSP

# Скрывать имя игрока в табе (списке игроков)
hide-in-tab-list: false

# Настройки сообщений
messages:
  reload-success: "&aRMBNametags: Конфигурация успешно перезагружена!"
  name-visible: "&aНик игрока &f{PLAYER_NAME}&a теперь виден."
  name-hidden: "&aНик игрока &f{PLAYER_NAME}&a теперь скрыт."
  all-names-visible: "&aНики всех игроков теперь видны."
  all-names-hidden: "&aНики всех игроков теперь скрыты."
  player-not-found: "&cИгрок &f{PLAYER_NAME}&c не найден или не в сети."
  no-permission: "&cУ вас нет прав для использования этой команды."
